name: release

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: feature/aha_fix

jobs:
  
  Get-Release:
    runs-on: ubuntu-latest
    steps:
      - name: New Release Publish
        uses: release-drafter/release-drafter@v5
        with:
          publish : true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
